var totNumOfItems="135";
var numOfChargingStationItems="133";
var numOfSubstationProjects="1";
var numOfLowspeedVehicles="0";
var cityData=[{
"city":"南京市",
"numOfChargingStationItems":"5",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"5",
"toBeConstructed":"1",
"underConstruction":"0",
"hysteresis":"5",
"completed":"0",
"projectList":[{
"name":"国网客服中心南方分中心",
"area":"江宁区",
"totAmt":"169.9603",
"prvnRatioAmt":"100%-16996.03",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间待审核",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"东华红山汽车生活广场红山路",
"area":"玄武区",
"totAmt":"178.4100",
"prvnRatioAmt":"100%-17841",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"",
"area":"秦淮区",
"totAmt":"63.0000",
"prvnRatioAmt":"100%-6300",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"暂存",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"宿迁市义务商贸城公交场站",
"area":"",
"totAmt":"225.49",
"prvnRatioAmt":"100%-22549",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"宿迁市雪枫公园枢纽站停车场分布式桩",
"area":"",
"totAmt":"181.88",
"prvnRatioAmt":"100%-18188",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"江宁区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"玄武区",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"秦淮区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
}],
"stationClassification":[{
"name":"专用（单位内部）",
"value":"1"
},
{
"name":"公交",
"value":"3"
},
{
"name":"城市公共",
"value":"1"
}],
"count1":"4"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"苏州市",
"numOfChargingStationItems":"52",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"52",
"toBeConstructed":"14",
"underConstruction":"2",
"hysteresis":"52",
"completed":"9",
"projectList":[{
"name":"渔洋街首末站",
"area":"吴中区",
"totAmt":"178.877",
"prvnRatioAmt":"100%-17887.7",
"selfproportionAmt":"0%-0",
"planCycle":"68",
"actlCycle":"1",
"status":"完成验收",
"projectSchedule":[{
"name":"土建施工",
"startTime":"2019-12-16",
"endTime":"2020-02-07",
"estimatedTm":"2020-02-07",
"cycle":"54",
"actlCycle":"1"
},
{
"name":"设备安装",
"startTime":"2020-02-10",
"endTime":"2020-02-11",
"estimatedTm":"2020-02-11",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备调试",
"startTime":"2020-02-13",
"endTime":"2020-02-14",
"estimatedTm":"2020-02-14",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备送电",
"startTime":"2020-02-12",
"endTime":"2020-02-12",
"estimatedTm":"2020-02-12",
"cycle":"1",
"actlCycle":"1"
},
{
"name":"进场前准备",
"startTime":"2019-12-09",
"endTime":"2019-12-13",
"estimatedTm":"2019-12-13",
"cycle":"5",
"actlCycle":"1"
}],
"constructionProcess":[{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/10006136daafb7457.jpg"],
"time":"2021-09-07",
"schedule":"1",
"status":"1",
"content":"补录项目"
},
{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/10006136daafb7457.jpg"],
"time":"2021-09-07",
"schedule":"1",
"status":"1",
"content":"补录项目"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/10006136daafb7457.jpg"],
"time":"2021-09-07",
"schedule":"1",
"status":"1",
"content":"补录项目"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/10006136daafb7457.jpg"],
"time":"2021-09-07",
"schedule":"1",
"status":"1",
"content":"补录项目"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/10006136daafb7457.jpg"],
"time":"2021-09-07",
"schedule":"1",
"status":"1",
"content":"补录项目"
}]
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"totAmt":"305.3571",
"prvnRatioAmt":"100%-30535.71",
"selfproportionAmt":"0%-0",
"planCycle":"68",
"actlCycle":"2",
"status":"完成验收",
"projectSchedule":[{
"name":"土建施工",
"startTime":"2019-12-16",
"endTime":"2020-02-07",
"estimatedTm":"2020-02-07",
"cycle":"54",
"actlCycle":"1"
},
{
"name":"设备安装",
"startTime":"2020-02-10",
"endTime":"2020-02-11",
"estimatedTm":"2020-02-11",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备调试",
"startTime":"2020-02-13",
"endTime":"2020-02-14",
"estimatedTm":"2020-02-14",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备送电",
"startTime":"2020-02-12",
"endTime":"2020-02-12",
"estimatedTm":"2020-02-12",
"cycle":"1",
"actlCycle":"1"
},
{
"name":"进场前准备",
"startTime":"2019-12-09",
"endTime":"2019-12-13",
"estimatedTm":"2019-12-13",
"cycle":"5",
"actlCycle":"2"
}],
"constructionProcess":[{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-07",
"schedule":"1",
"status":"1",
"content":"补录项目"
},
{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
}]
},
{
"name":"东山公交首末站",
"area":"吴中区",
"totAmt":"189.7460",
"prvnRatioAmt":"100%-18974.6",
"selfproportionAmt":"0%-0",
"planCycle":"68",
"actlCycle":"1",
"status":"完成验收",
"projectSchedule":[{
"name":"土建施工",
"startTime":"2019-12-16",
"endTime":"2020-02-07",
"estimatedTm":"2020-02-07",
"cycle":"54",
"actlCycle":"1"
},
{
"name":"设备安装",
"startTime":"2020-02-10",
"endTime":"2020-02-11",
"estimatedTm":"2020-02-11",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备调试",
"startTime":"2020-02-13",
"endTime":"2020-02-14",
"estimatedTm":"2020-02-14",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备送电",
"startTime":"2020-02-12",
"endTime":"2020-02-12",
"estimatedTm":"2020-02-12",
"cycle":"1",
"actlCycle":"1"
},
{
"name":"进场前准备",
"startTime":"2019-12-09",
"endTime":"2019-12-13",
"estimatedTm":"2019-12-13",
"cycle":"5",
"actlCycle":"1"
}],
"constructionProcess":[{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"完成"
},
{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"完成"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"完成"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"完成"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"完成"
}]
},
{
"name":"金山路停保场2期",
"area":"高新区",
"totAmt":"331.2304",
"prvnRatioAmt":"100%-33123.04",
"selfproportionAmt":"0%-0",
"planCycle":"68",
"actlCycle":"1",
"status":"完成验收",
"projectSchedule":[{
"name":"土建施工",
"startTime":"2019-12-16",
"endTime":"2020-02-07",
"estimatedTm":"2020-02-07",
"cycle":"54",
"actlCycle":"1"
},
{
"name":"设备安装",
"startTime":"2020-02-10",
"endTime":"2020-02-11",
"estimatedTm":"2020-02-11",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备调试",
"startTime":"2020-02-13",
"endTime":"2020-02-14",
"estimatedTm":"2020-02-14",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备送电",
"startTime":"2020-02-12",
"endTime":"2020-02-12",
"estimatedTm":"2020-02-12",
"cycle":"1",
"actlCycle":"1"
},
{
"name":"进场前准备",
"startTime":"2019-12-09",
"endTime":"2019-12-13",
"estimatedTm":"2019-12-13",
"cycle":"5",
"actlCycle":"1"
}],
"constructionProcess":[{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
}]
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"totAmt":"180.2145",
"prvnRatioAmt":"100%-18021.45",
"selfproportionAmt":"0%-0",
"planCycle":"68",
"actlCycle":"1",
"status":"完成验收",
"projectSchedule":[{
"name":"土建施工",
"startTime":"2019-12-16",
"endTime":"2020-02-07",
"estimatedTm":"2020-02-07",
"cycle":"54",
"actlCycle":"1"
},
{
"name":"设备安装",
"startTime":"2020-02-10",
"endTime":"2020-02-11",
"estimatedTm":"2020-02-11",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备调试",
"startTime":"2020-02-13",
"endTime":"2020-02-14",
"estimatedTm":"2020-02-14",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备送电",
"startTime":"2020-02-12",
"endTime":"2020-02-12",
"estimatedTm":"2020-02-12",
"cycle":"1",
"actlCycle":"1"
},
{
"name":"进场前准备",
"startTime":"2019-12-09",
"endTime":"2019-12-13",
"estimatedTm":"2019-12-13",
"cycle":"5",
"actlCycle":"1"
}],
"constructionProcess":[{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
}]
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"totAmt":"314.7075",
"prvnRatioAmt":"100%-31470.75",
"selfproportionAmt":"0%-0",
"planCycle":"68",
"actlCycle":"1",
"status":"完成验收",
"projectSchedule":[{
"name":"土建施工",
"startTime":"2019-12-16",
"endTime":"2020-02-07",
"estimatedTm":"2020-02-07",
"cycle":"54",
"actlCycle":"1"
},
{
"name":"设备安装",
"startTime":"2020-02-10",
"endTime":"2020-02-11",
"estimatedTm":"2020-02-11",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备调试",
"startTime":"2020-02-13",
"endTime":"2020-02-14",
"estimatedTm":"2020-02-14",
"cycle":"2",
"actlCycle":"1"
},
{
"name":"设备送电",
"startTime":"2020-02-12",
"endTime":"2020-02-12",
"estimatedTm":"2020-02-12",
"cycle":"1",
"actlCycle":"1"
},
{
"name":"进场前准备",
"startTime":"2019-12-09",
"endTime":"2019-12-13",
"estimatedTm":"2019-12-13",
"cycle":"5",
"actlCycle":"1"
}],
"constructionProcess":[{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"进场前准备",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"土建施工",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备安装",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备送电",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
},
{
"name":"设备调试",
"imageList":["http://47.98.113.113:8083/project/Public/Uploads/94256136db658f2b3.jpg"],
"time":"2021-09-08",
"schedule":"1",
"status":"1",
"content":"补录"
}]
}],
"eachAreaCondition":[{
"area":"吴中区",
"toBeConstructed":"4",
"underConstruction":"0",
"completed":"4",
"hysteresis":"9"
},
{
"area":"吴江区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"2"
},
{
"area":"太仓市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"5"
},
{
"area":"姑苏区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"1",
"hysteresis":"1"
},
{
"area":"常熟市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"2"
},
{
"area":"张家港市",
"toBeConstructed":"8",
"underConstruction":"1",
"completed":"0",
"hysteresis":"16"
},
{
"area":"昆山市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"4"
},
{
"area":"相城区",
"toBeConstructed":"1",
"underConstruction":"1",
"completed":"0",
"hysteresis":"5"
},
{
"area":"虎丘区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"高新区",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"4",
"hysteresis":"5"
}],
"stationClassification":[{
"name":"专用（单位内部）",
"value":"1"
},
{
"name":"公交",
"value":"13"
},
{
"name":"城市公共",
"value":"37"
},
{
"name":"高速",
"value":"1"
}],
"count1":"27"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"无锡市",
"numOfChargingStationItems":"10",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"10",
"toBeConstructed":"1",
"underConstruction":"0",
"hysteresis":"10",
"completed":"0",
"projectList":[{
"name":"宜兴市和桥镇人民政府便民广场",
"area":"宜兴市",
"totAmt":"36.0000",
"prvnRatioAmt":"100%-3600",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项待审核",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":" 无锡锡山区锡北镇丰田苑（一期、二期）、斗山苑社区、怡丰苑、丰泰苑停车场",
"area":"锡山区",
"totAmt":"92.0000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-9200",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"无锡锡山区东港红豆首府",
"area":"锡山区",
"totAmt":"31.5000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-3150",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"无锡滨湖区大统华建筑路店地面停车场",
"area":"滨湖区",
"totAmt":"144.0000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-14400",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"无锡梁溪区华商物流地面停车场",
"area":"梁溪区",
"totAmt":"48.0000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-4800",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"无锡新区江溪街道叙丰",
"area":"新吴区",
"totAmt":"120.0000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-12000",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"宜兴市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"新吴区",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0",
"hysteresis":"3"
},
{
"area":"梁溪区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"江阴市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"滨湖区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"锡山区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"3"
}],
"stationClassification":[{
"name":"公交",
"value":"1"
},
{
"name":"城市公共",
"value":"9"
}],
"count1":"9"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"南通市",
"numOfChargingStationItems":"22",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"22",
"toBeConstructed":"1",
"underConstruction":"0",
"hysteresis":"22",
"completed":"0",
"projectList":[{
"name":"南通市如东县城北公交站",
"area":"如东县",
"totAmt":"296.39",
"prvnRatioAmt":"100%-29639",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"南通市如东县袁庄公交站",
"area":"如东县",
"totAmt":"96.0000",
"prvnRatioAmt":"100%-9600",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间待审核",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"南通市海门区大千回车场",
"area":"海门市",
"totAmt":"120.0000",
"prvnRatioAmt":"100%-12000",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"南通市如东县长沙公交站",
"area":"如东县",
"totAmt":"112.56",
"prvnRatioAmt":"100%-11256",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间待审核",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"海门区火车站站前广场",
"area":"海门市",
"totAmt":"120.0000",
"prvnRatioAmt":"100%-12000",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"南通市海门区三阳镇公交站停车场",
"area":"海门市",
"totAmt":"120.0000",
"prvnRatioAmt":"100%-12000",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"启东市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"如东县",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0",
"hysteresis":"4"
},
{
"area":"如皋市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"崇川区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"海安市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"10"
},
{
"area":"海门市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"4"
}],
"stationClassification":[{
"name":"专用（单位内部）",
"value":"1"
},
{
"name":"公交",
"value":"21"
}],
"count1":"21"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"徐州市",
"numOfChargingStationItems":"13",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"13",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"13",
"completed":"0",
"projectList":[{
"name":"煤港路",
"area":"鼓楼区",
"totAmt":"105.8000",
"prvnRatioAmt":"100%-10580",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"煤港路62号",
"area":"鼓楼区",
"totAmt":"23.2274",
"prvnRatioAmt":"100%-2322.74",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"御景路",
"area":"泉山区",
"totAmt":"26.7670",
"prvnRatioAmt":"100%-2676.7",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"渤海路",
"area":"云龙区",
"totAmt":"26.5586",
"prvnRatioAmt":"100%-2655.86",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"G310(连共线)",
"area":"铜山区",
"totAmt":"26.3847",
"prvnRatioAmt":"100%-2638.47",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"山深线",
"area":"新沂市",
"totAmt":"26.3090",
"prvnRatioAmt":"100%-2630.9",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"云龙区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"3"
},
{
"area":"新沂市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"3"
},
{
"area":"泉山区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"邳州市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"2"
},
{
"area":"铜山区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"鼓楼区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"3"
}],
"stationClassification":[{
"name":"城市公共",
"value":"12"
},
{
"name":"环卫",
"value":"1"
}],
"count1":"13"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"连云港市",
"numOfChargingStationItems":"0",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"淮安市",
"numOfChargingStationItems":"1",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"1",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"1",
"completed":"0",
"projectList":[{
"name":"漕运东路8号",
"area":"清江浦区",
"totAmt":"16.0000",
"prvnRatioAmt":"100%-1600",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"暂存",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"清江浦区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
}],
"stationClassification":[{
"name":"城市公共",
"value":"1"
}],
"count1":"1"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"泰州市",
"numOfChargingStationItems":"2",
"numOfSubstationProjects":"1",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"2",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"2",
"completed":"0",
"projectList":[{
"name":"胡庄镇宣传文化中心广场西侧",
"area":"高港区",
"totAmt":"48.0000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-4800",
"planCycle":"1",
"actlCycle":"1",
"status":"暂存",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"姜堰邮政速递物流停车场",
"area":"姜堰区",
"totAmt":"9.8000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-980",
"planCycle":"1",
"actlCycle":"1",
"status":"暂存",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"姜堰区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"高港区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
}],
"stationClassification":[{
"name":"公交",
"value":"1"
},
{
"name":"物流",
"value":"1"
}],
"count1":"2"
},
"repData":{
"totNumOfItems":"1",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"1",
"completed":"0",
"projectList":[{
"name":"泰州市医药高新区凤凰西路2号",
"area":"海陵区",
"totAmt":"30.13",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-3013",
"planCycle":"1",
"actlCycle":"1",
"status":"暂存",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"海陵区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
}],
"stationClassification":[{
"name":"乘用车",
"value":"1"
}],
"count1":"1"
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"常州市",
"numOfChargingStationItems":"3",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"3",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"3",
"completed":"0",
"projectList":[{
"name":"新平路武进公交中心站停车场内",
"area":"武进区",
"totAmt":"185",
"prvnRatioAmt":"100%-18500",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"溧阳市燕山新区燕城大道205号溧阳高铁站公交停车场内",
"area":"溧阳市",
"totAmt":"105",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-10500",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"长江北路常州北站公交中心停车场内",
"area":"新北区",
"totAmt":"115",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-11500",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"新北区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"武进区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"溧阳市",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
}],
"stationClassification":[{
"name":"公交",
"value":"3"
}],
"count1":"3"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"扬州市",
"numOfChargingStationItems":"9",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"9",
"toBeConstructed":"1",
"underConstruction":"0",
"hysteresis":"9",
"completed":"0",
"projectList":[{
"name":"文昌中路386号",
"area":"广陵区",
"totAmt":"19.5000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-1950",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"文昌中路386号",
"area":"广陵区",
"totAmt":"9.3000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-930",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"文昌中路386号",
"area":"广陵区",
"totAmt":"11.4000",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-1140",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"文昌中路386号",
"area":"广陵区",
"totAmt":"38.0658",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-3806.58",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"文昌中路386号",
"area":"广陵区",
"totAmt":"24.8393",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-2483.93",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"文昌中路386号",
"area":"广陵区",
"totAmt":"77.4052",
"prvnRatioAmt":"0%-0",
"selfproportionAmt":"100%-7740.52",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"广陵区",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0",
"hysteresis":"9"
}],
"stationClassification":[{
"name":"公交",
"value":"1"
},
{
"name":"城市公共",
"value":"2"
},
{
"name":"邮政",
"value":"6"
}],
"count1":"8"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"镇江市",
"numOfChargingStationItems":"0",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"盐城市",
"numOfChargingStationItems":"5",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"5",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"5",
"completed":"0",
"projectList":[{
"name":"盐塘河公园",
"area":"盐都区",
"totAmt":"125.9328",
"prvnRatioAmt":"100%-12593.28",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"聚龙湖公园",
"area":"盐都区",
"totAmt":"122.4706",
"prvnRatioAmt":"100%-12247.06",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"欧风花街",
"area":"盐都区",
"totAmt":"141.4269",
"prvnRatioAmt":"100%-14142.69",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"南海公园",
"area":"盐都区",
"totAmt":"138.0870",
"prvnRatioAmt":"100%-13808.7",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"大数据产业园区",
"area":"盐都区",
"totAmt":"135.4488",
"prvnRatioAmt":"100%-13544.88",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"初步立项审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"盐都区",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0",
"hysteresis":"5"
}],
"stationClassification":[{
"name":"城市公共",
"value":"5"
}],
"count1":"5"
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
},
{
"city":"宿迁市",
"numOfChargingStationItems":"11",
"numOfSubstationProjects":"0",
"numOfLowspeedVehicles":"0",
"chaData":{
"totNumOfItems":"11",
"toBeConstructed":"11",
"underConstruction":"0",
"hysteresis":"11",
"completed":"0",
"projectList":[{
"name":"沭阳县城东迎宾大道东延伸段南侧，新205国道西侧，沭阳民生公交交通有限公司内部停车场",
"area":"沭阳县",
"totAmt":"87.2938",
"prvnRatioAmt":"100%-8729.38",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"可研审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"宿迁市宿城区宿支路南侧宿迁市第一人民医院公交枢纽站停车场",
"area":"泗洪县",
"totAmt":"494.54",
"prvnRatioAmt":"100%-49454",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"宿迁市宿城区埠子汽车客运站公共停车场内",
"area":"宿城区",
"totAmt":"144.0000",
"prvnRatioAmt":"100%-14400",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"宿迁市龙河汽车客运站公共停车场内",
"area":"宿城区",
"totAmt":"192.0000",
"prvnRatioAmt":"100%-19200",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"宿迁市罗圩汽车客运站公共停车场内",
"area":"宿城区",
"totAmt":"240.0000",
"prvnRatioAmt":"100%-24000",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间审核通过",
"projectSchedule":[],
"constructionProcess":[]
},
{
"name":"宿迁市城西公交首末站停车场内",
"area":"宿城区",
"totAmt":"110.22",
"prvnRatioAmt":"100%-11022",
"selfproportionAmt":"0%-0",
"planCycle":"1",
"actlCycle":"1",
"status":"关键节点时间审核通过",
"projectSchedule":[],
"constructionProcess":[]
}],
"eachAreaCondition":[{
"area":"宿城区",
"toBeConstructed":"7",
"underConstruction":"0",
"completed":"0",
"hysteresis":"7"
},
{
"area":"宿豫区",
"toBeConstructed":"2",
"underConstruction":"0",
"completed":"0",
"hysteresis":"2"
},
{
"area":"沭阳县",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
},
{
"area":"泗洪县",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0",
"hysteresis":"1"
}],
"stationClassification":[{
"name":"公交",
"value":"11"
}]
},
"repData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
},
"lowData":{
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"hysteresis":"0",
"completed":"0",
"eachAreaCondition":[],
"stationClassification":[]
}
}];
var chaData={
"totNumOfItems":"133",
"toBeConstructed":"29",
"underConstruction":"2",
"numOfProjectsUnderConstruction":"2",
"hysteresis":"133",
"completed":"9",
"numOfProjectsInOperation":"9",
"numOfItemsInStg":"93",
"numOfProjectsInFeasibilityStdy":"3",
"numOfProjectsInBidding":"0",
"numOfProjectsUnderContract":"0",
"numOfItemsInAcceptance":"1",
"top10WithTheLongestConstructionPd":[{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10WithTheShortestConstructionPd":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
}],
"theLongestPowerCycleTop10":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10WithTheShortestPowerCycle":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10NewlyBuiltProjects":[{
"name":"宿迁市雪枫公园枢纽站停车场分布式桩",
"area":"",
"startTime":"",
"endTime":""
},
{
"name":"宿迁市义务商贸城公交场站",
"area":"",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"常熟市虞山高新产业园客运站",
"area":"常熟市",
"startTime":"",
"endTime":""
},
{
"name":"张家港市人民西路悦华苑小区停车场",
"area":"张家港市",
"startTime":"",
"endTime":""
}],
"top10RecentlyCompletedProjects":[{
"name":"渔洋街首末站",
"area":"吴中区",
"startTime":"2021/09/07",
"endTime":"2021/09/07"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"startTime":"2021/09/07",
"endTime":"2021/09/08"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"startTime":"2019/12/11",
"endTime":"2020/02/18"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"startTime":"2019/12/09",
"endTime":"2020/02/14"
}],
"numOfMapProjects":[{
"city":"南京市",
"value":"5",
"children":[
{
 "area":"六合区",
 "value":"1"
},{
 "area":"浦口区",
 "value":"0"
},{
 "area":"栖霞区",
 "value":"2"
},{
 "area":"鼓楼区",
 "value":"0"
},{
 "area":"玄武区",
 "value":"0"
},{
 "area":"建邺区",
 "value":"0"
},{
 "area":"秦淮区",
 "value":"0"
},{
 "area":"雨花台区",
 "value":"0"
},{
 "area":"江宁区",
 "value":"0"
},{
 "area":"溧水区",
 "value":"0"
},{
 "area":"高淳区",
 "value":"0"
}
]
},
{
"city":"苏州市",
"value":"52",
"children":[
{
 "area":"张家港区",
 "value":"1"
},{
 "area":"常熟区",
 "value":"0"
},{
 "area":"相城区",
 "value":"2"
},{
 "area":"太仓区",
 "value":"0"
},{
 "area":"虎丘区",
 "value":"0"
},{
 "area":"姑苏区",
 "value":"0"
},{
 "area":"工业园区",
 "value":"0"
},{
 "area":"昆山区",
 "value":"0"
},{
 "area":"吴中区",
 "value":"0"
},{
 "area":"吴江区",
 "value":"0"
}
]
},
{
"city":"无锡市",
"value":"10",
"children":[
{
 "area":"江阴市",
 "value":"1"
},{
 "area":"惠山区",
 "value":"0"
},{
 "area":"锡山区",
 "value":"2"
},{
 "area":"梁溪区",
 "value":"0"
},{
 "area":"滨湖区",
 "value":"0"
},{
 "area":"新吴区",
 "value":"0"
},{
 "area":"宜兴市",
 "value":"0"
}
]
},
{
"city":"南通市",
"value":"22",
"children":[
{
 "area":"海安市",
 "value":"1"
},{
 "area":"如皋市",
 "value":"0"
},{
 "area":"如东县",
 "value":"2"
},{
 "area":"通州区",
 "value":"0"
},{
 "area":"崇川区",
 "value":"0"
},{
 "area":"海门区",
 "value":"0"
},{
 "area":"启东市",
 "value":"0"
}
]
},
{
"city":"徐州市",
"value":"13",
"children":[
{
 "area":"丰县",
 "value":"1"
},{
 "area":"沛县",
 "value":"0"
},{
 "area":"鼓楼区",
 "value":"2"
},{
 "area":"泉山区",
 "value":"0"
},{
 "area":"云龙区",
 "value":"0"
},{
 "area":"贾汪区",
 "value":"0"
},{
 "area":"铜山区",
 "value":"0"
},{
 "area":"邳州市",
 "value":"0"
},{
 "area":"新沂市",
 "value":"0"
},{
 "area":"睢宁县",
 "value":"0"
}
]
},
{
"city":"连云港市",
"value":"0",
"children":[
{
 "area":"赣榆区",
 "value":"1"
},{
 "area":"东海县",
 "value":"0"
},{
 "area":"海州区",
 "value":"2"
},{
 "area":"连云区",
 "value":"0"
},{
 "area":"港云县",
 "value":"0"
},{
 "area":"灌南县",
 "value":"0"
}
]
},
{
"city":"淮安市",
"value":"1",
"children":[
{
 "area":"涟水区",
 "value":"1"
},{
 "area":"淮阴区",
 "value":"0"
},{
 "area":"清江浦区",
 "value":"2"
},{
 "area":"淮安区",
 "value":"0"
},{
 "area":"洪泽区",
 "value":"0"
},{
 "area":"盱眙县",
 "value":"0"
},{
 "area":"金湖县",
 "value":"0"
}
]
},
{
"city":"泰州市",
"value":"2",
"children":[
{
 "area":"兴化市",
 "value":"1"
},{
 "area":"海陵区",
 "value":"0"
},{
 "area":"姜堰区",
 "value":"2"
},{
 "area":"高港区",
 "value":"0"
},{
 "area":"泰兴市",
 "value":"0"
},{
 "area":"靖江市",
 "value":"0"
}
]
},
{
"city":"常州市",
"value":"3",
"children":[
{
 "area":"新北区",
 "value":"1"
},{
 "area":"钟楼区",
 "value":"0"
},{
 "area":"天宁区",
 "value":"2"
},{
 "area":"武进区",
 "value":"0"
},{
 "area":"金坛区",
 "value":"0"
},{
 "area":"溧阳市",
 "value":"0"
}
]
},
{
"city":"扬州市",
"value":"9",
"children":[
{
 "area":"宝应县",
 "value":"1"
},{
 "area":"高邮市",
 "value":"0"
},{
 "area":"仪征市",
 "value":"2"
},{
 "area":"邗江区",
 "value":"0"
},{
 "area":"广陵区",
 "value":"0"
},{
 "area":"江都区",
 "value":"0"
}
]
},
{
"city":"镇江市",
"value":"0",
"children":[
{
 "area":"句容市",
 "value":"1"
},{
 "area":"丹徒区",
 "value":"0"
},{
 "area":"润州区",
 "value":"2"
},{
 "area":"京口区",
 "value":"0"
},{
 "area":"扬中市",
 "value":"0"
},{
 "area":"丹阳市",
 "value":"0"
}
]
},
{
"city":"盐城市",
"value":"5",
"children":[
{
 "area":"响水县",
 "value":"1"
},{
 "area":"滨海县",
 "value":"0"
},{
 "area":"阜宁县",
 "value":"2"
},{
 "area":"射阳县",
 "value":"0"
},{
 "area":"建湖县",
 "value":"0"
},{
 "area":"亭湖区",
 "value":"0"
},{
 "area":"盐都区",
 "value":"0"
},{
 "area":"大丰区",
 "value":"0"
},{
 "area":"东台区",
 "value":"0"
}
]
},
{
"city":"宿迁市",
"value":"11",
"children":[
{
 "area":"沭阳县",
 "value":"1"
},{
 "area":"宿豫区",
 "value":"0"
},{
 "area":"宿城区",
 "value":"2"
},{
 "area":"泗阳县",
 "value":"0"
},{
 "area":"泗洪县",
 "value":"0"
}
]
}],
"totNumOfInvestProjectsIn13Cities":{
"within2Million":"111",
"moreThan2Million":"22",
"provincialCoWithin2Million":"21",
"provincialCoOvr2Million":"112"
},
"numOfInvestProjectsIn13Cities":[{
"city":"南京市",
"within2Million":"5",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"5"
},
{
"city":"苏州市",
"within2Million":"52",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"52"
},
{
"city":"无锡市",
"within2Million":"2",
"moreThan2Million":"8",
"provincialCoWithin2Million":"8",
"provincialCoOvr2Million":"2"
},
{
"city":"南通市",
"within2Million":"21",
"moreThan2Million":"1",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"22"
},
{
"city":"徐州市",
"within2Million":"13",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"13"
},
{
"city":"连云港市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"淮安市",
"within2Million":"1",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"1"
},
{
"city":"泰州市",
"within2Million":"0",
"moreThan2Million":"2",
"provincialCoWithin2Million":"2",
"provincialCoOvr2Million":"0"
},
{
"city":"常州市",
"within2Million":"1",
"moreThan2Million":"2",
"provincialCoWithin2Million":"2",
"provincialCoOvr2Million":"1"
},
{
"city":"扬州市",
"within2Million":"0",
"moreThan2Million":"9",
"provincialCoWithin2Million":"9",
"provincialCoOvr2Million":"0"
},
{
"city":"镇江市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"盐城市",
"within2Million":"5",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"5"
},
{
"city":"宿迁市",
"within2Million":"11",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"11"
}],
"projectStsInThePast6Months":[{
"date":"10月",
"numOfNewProjects":"67",
"numOfProjectsCompleted":"0"
},
{
"date":"09月",
"numOfNewProjects":"54",
"numOfProjectsCompleted":"0"
},
{
"date":"08月",
"numOfNewProjects":"12",
"numOfProjectsCompleted":"0"
},
{
"date":"07月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"06月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"05月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
}],
"stationClassification":[{
"name":"专用（单位内部）",
"value":"3"
},
{
"name":"公交",
"value":"54"
},
{
"name":"城市公共",
"value":"67"
},
{
"name":"物流",
"value":"1"
},
{
"name":"环卫",
"value":"1"
},
{
"name":"邮政",
"value":"6"
},
{
"name":"高速",
"value":"1"
}],
"totStationClassification":"133",
"proportionOfProjectsIn13Cities":[{
"city":"南京市",
"totNumOfItems":"5",
"toBeConstructed":"5",
"underConstruction":"0",
"completed":"0"
},
{
"city":"苏州市",
"totNumOfItems":"52",
"toBeConstructed":"52",
"underConstruction":"2",
"completed":"9"
},
{
"city":"无锡市",
"totNumOfItems":"10",
"toBeConstructed":"10",
"underConstruction":"0",
"completed":"0"
},
{
"city":"南通市",
"totNumOfItems":"22",
"toBeConstructed":"22",
"underConstruction":"0",
"completed":"0"
},
{
"city":"徐州市",
"totNumOfItems":"13",
"toBeConstructed":"13",
"underConstruction":"0",
"completed":"0"
},
{
"city":"连云港市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"淮安市",
"totNumOfItems":"1",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0"
},
{
"city":"泰州市",
"totNumOfItems":"2",
"toBeConstructed":"2",
"underConstruction":"0",
"completed":"0"
},
{
"city":"常州市",
"totNumOfItems":"3",
"toBeConstructed":"3",
"underConstruction":"0",
"completed":"0"
},
{
"city":"扬州市",
"totNumOfItems":"9",
"toBeConstructed":"9",
"underConstruction":"0",
"completed":"0"
},
{
"city":"镇江市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"盐城市",
"totNumOfItems":"5",
"toBeConstructed":"5",
"underConstruction":"0",
"completed":"0"
},
{
"city":"宿迁市",
"totNumOfItems":"11",
"toBeConstructed":"11",
"underConstruction":"0",
"completed":"0"
}]
};
var repData={
"totNumOfItems":"133",
"toBeConstructed":"29",
"underConstruction":"2",
"numOfProjectsUnderConstruction":"2",
"hysteresis":"133",
"completed":"9",
"numOfProjectsInOperation":"9",
"numOfItemsInStg":"93",
"numOfProjectsInFeasibilityStdy":"3",
"numOfProjectsInBidding":"0",
"numOfProjectsUnderContract":"0",
"numOfItemsInAcceptance":"1",
"top10WithTheLongestConstructionPd":[{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10WithTheShortestConstructionPd":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
}],
"theLongestPowerCycleTop10":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10WithTheShortestPowerCycle":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10NewlyBuiltProjects":[{
"name":"宿迁市雪枫公园枢纽站停车场分布式桩",
"area":"",
"startTime":"",
"endTime":""
},
{
"name":"宿迁市义务商贸城公交场站",
"area":"",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"常熟市虞山高新产业园客运站",
"area":"常熟市",
"startTime":"",
"endTime":""
},
{
"name":"张家港市人民西路悦华苑小区停车场",
"area":"张家港市",
"startTime":"",
"endTime":""
}],
"top10RecentlyCompletedProjects":[{
"name":"渔洋街首末站",
"area":"吴中区",
"startTime":"2021/09/07",
"endTime":"2021/09/07"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"startTime":"2021/09/07",
"endTime":"2021/09/08"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"startTime":"2019/12/11",
"endTime":"2020/02/18"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"startTime":"2019/12/09",
"endTime":"2020/02/14"
}],
"numOfMapProjects":[{
"city":"南京市",
"value":"0",
"children":[
{
 "area":"六合区",
 "value":"1"
},{
 "area":"浦口区",
 "value":"0"
},{
 "area":"栖霞区",
 "value":"2"
},{
 "area":"鼓楼区",
 "value":"0"
},{
 "area":"玄武区",
 "value":"0"
},{
 "area":"建邺区",
 "value":"0"
},{
 "area":"秦淮区",
 "value":"0"
},{
 "area":"雨花台区",
 "value":"0"
},{
 "area":"江宁区",
 "value":"0"
},{
 "area":"溧水区",
 "value":"0"
},{
 "area":"高淳区",
 "value":"0"
}
]
},
{
"city":"苏州市",
"value":"0",
"children":[
{
 "area":"张家港区",
 "value":"1"
},{
 "area":"常熟区",
 "value":"0"
},{
 "area":"相城区",
 "value":"2"
},{
 "area":"太仓区",
 "value":"0"
},{
 "area":"虎丘区",
 "value":"0"
},{
 "area":"姑苏区",
 "value":"0"
},{
 "area":"工业园区",
 "value":"0"
},{
 "area":"昆山区",
 "value":"0"
},{
 "area":"吴中区",
 "value":"0"
},{
 "area":"吴江区",
 "value":"0"
}
]
},
{
"city":"无锡市",
"value":"0",
"children":[
{
 "area":"江阴市",
 "value":"1"
},{
 "area":"惠山区",
 "value":"0"
},{
 "area":"锡山区",
 "value":"2"
},{
 "area":"梁溪区",
 "value":"0"
},{
 "area":"滨湖区",
 "value":"0"
},{
 "area":"新吴区",
 "value":"0"
},{
 "area":"宜兴市",
 "value":"0"
}
]
},
{
"city":"南通市",
"value":"0",
"children":[
{
 "area":"海安市",
 "value":"1"
},{
 "area":"如皋市",
 "value":"0"
},{
 "area":"如东县",
 "value":"2"
},{
 "area":"通州区",
 "value":"0"
},{
 "area":"崇川区",
 "value":"0"
},{
 "area":"海门区",
 "value":"0"
},{
 "area":"启东市",
 "value":"0"
}
]
},
{
"city":"徐州市",
"value":"0",
"children":[
{
 "area":"丰县",
 "value":"1"
},{
 "area":"沛县",
 "value":"0"
},{
 "area":"鼓楼区",
 "value":"2"
},{
 "area":"泉山区",
 "value":"0"
},{
 "area":"云龙区",
 "value":"0"
},{
 "area":"贾汪区",
 "value":"0"
},{
 "area":"铜山区",
 "value":"0"
},{
 "area":"邳州市",
 "value":"0"
},{
 "area":"新沂市",
 "value":"0"
},{
 "area":"睢宁县",
 "value":"0"
}
]
},
{
"city":"连云港市",
"value":"0",
"children":[
{
 "area":"赣榆区",
 "value":"1"
},{
 "area":"东海县",
 "value":"0"
},{
 "area":"海州区",
 "value":"2"
},{
 "area":"连云区",
 "value":"0"
},{
 "area":"港云县",
 "value":"0"
},{
 "area":"灌南县",
 "value":"0"
}
]
},
{
"city":"淮安市",
"value":"0",
"children":[
{
 "area":"涟水区",
 "value":"1"
},{
 "area":"淮阴区",
 "value":"0"
},{
 "area":"清江浦区",
 "value":"2"
},{
 "area":"淮安区",
 "value":"0"
},{
 "area":"洪泽区",
 "value":"0"
},{
 "area":"盱眙县",
 "value":"0"
},{
 "area":"金湖县",
 "value":"0"
}
]
},
{
"city":"泰州市",
"value":"1",
"children":[
{
 "area":"兴化市",
 "value":"1"
},{
 "area":"海陵区",
 "value":"0"
},{
 "area":"姜堰区",
 "value":"2"
},{
 "area":"高港区",
 "value":"0"
},{
 "area":"泰兴市",
 "value":"0"
},{
 "area":"靖江市",
 "value":"0"
}
]
},
{
"city":"常州市",
"value":"0",
"children":[
{
 "area":"新北区",
 "value":"1"
},{
 "area":"钟楼区",
 "value":"0"
},{
 "area":"天宁区",
 "value":"2"
},{
 "area":"武进区",
 "value":"0"
},{
 "area":"金坛区",
 "value":"0"
},{
 "area":"溧阳市",
 "value":"0"
}
]
},
{
"city":"扬州市",
"value":"0",
"children":[
{
 "area":"宝应县",
 "value":"1"
},{
 "area":"高邮市",
 "value":"0"
},{
 "area":"仪征市",
 "value":"2"
},{
 "area":"邗江区",
 "value":"0"
},{
 "area":"广陵区",
 "value":"0"
},{
 "area":"江都区",
 "value":"0"
}
]
},
{
"city":"镇江市",
"value":"0",
"children":[
{
 "area":"句容市",
 "value":"1"
},{
 "area":"丹徒区",
 "value":"0"
},{
 "area":"润州区",
 "value":"2"
},{
 "area":"京口区",
 "value":"0"
},{
 "area":"扬中市",
 "value":"0"
},{
 "area":"丹阳市",
 "value":"0"
}
]
},
{
"city":"盐城市",
"value":"0",
"children":[
{
 "area":"响水县",
 "value":"1"
},{
 "area":"滨海县",
 "value":"0"
},{
 "area":"阜宁县",
 "value":"2"
},{
 "area":"射阳县",
 "value":"0"
},{
 "area":"建湖县",
 "value":"0"
},{
 "area":"亭湖区",
 "value":"0"
},{
 "area":"盐都区",
 "value":"0"
},{
 "area":"大丰区",
 "value":"0"
},{
 "area":"东台区",
 "value":"0"
}
]
},
{
"city":"宿迁市",
"value":"0",
"children":[
{
 "area":"沭阳县",
 "value":"1"
},{
 "area":"宿豫区",
 "value":"0"
},{
 "area":"宿城区",
 "value":"2"
},{
 "area":"泗阳县",
 "value":"0"
},{
 "area":"泗洪县",
 "value":"0"
}
]
}],
"totNumOfInvestProjectsIn13Cities":{
"within2Million":"0",
"moreThan2Million":"1",
"provincialCoWithin2Million":"1",
"provincialCoOvr2Million":"0"
},
"numOfInvestProjectsIn13Cities":[{
"city":"南京市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"苏州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"无锡市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"南通市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"徐州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"连云港市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"淮安市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"泰州市",
"within2Million":"0",
"moreThan2Million":"1",
"provincialCoWithin2Million":"1",
"provincialCoOvr2Million":"0"
},
{
"city":"常州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"扬州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"镇江市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"盐城市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"宿迁市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
}],
"projectStsInThePast6Months":[{
"date":"10月",
"numOfNewProjects":"1",
"numOfProjectsCompleted":"0"
},
{
"date":"09月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"08月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"07月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"06月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"05月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
}],
"stationClassification":[],
"totStationClassification":"0",
"proportionOfProjectsIn13Cities":[{
"city":"南京市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"苏州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"无锡市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"南通市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"徐州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"连云港市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"淮安市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"泰州市",
"totNumOfItems":"1",
"toBeConstructed":"1",
"underConstruction":"0",
"completed":"0"
},
{
"city":"常州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"扬州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"镇江市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"盐城市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"宿迁市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
}]
};
var lowData={
"totNumOfItems":"133",
"toBeConstructed":"29",
"underConstruction":"2",
"numOfProjectsUnderConstruction":"2",
"hysteresis":"133",
"completed":"9",
"numOfProjectsInOperation":"9",
"numOfItemsInStg":"93",
"numOfProjectsInFeasibilityStdy":"3",
"numOfProjectsInBidding":"0",
"numOfProjectsUnderContract":"0",
"numOfItemsInAcceptance":"1",
"top10WithTheLongestConstructionPd":[{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10WithTheShortestConstructionPd":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
}],
"theLongestPowerCycleTop10":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10WithTheShortestPowerCycle":[{
"name":"渔洋街首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"cycle":"2"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"cycle":"1"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"cycle":"1"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"cycle":"1"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"cycle":"68"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"cycle":"70"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"cycle":"1"
}],
"top10NewlyBuiltProjects":[{
"name":"宿迁市雪枫公园枢纽站停车场分布式桩",
"area":"",
"startTime":"",
"endTime":""
},
{
"name":"宿迁市义务商贸城公交场站",
"area":"",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"文昌中路386号",
"area":"广陵区",
"startTime":"",
"endTime":""
},
{
"name":"常熟市虞山高新产业园客运站",
"area":"常熟市",
"startTime":"",
"endTime":""
},
{
"name":"张家港市人民西路悦华苑小区停车场",
"area":"张家港市",
"startTime":"",
"endTime":""
}],
"top10RecentlyCompletedProjects":[{
"name":"渔洋街首末站",
"area":"吴中区",
"startTime":"2021/09/07",
"endTime":"2021/09/07"
},
{
"name":"苏虞张连接线公交站",
"area":"姑苏区",
"startTime":"2021/09/07",
"endTime":"2021/09/08"
},
{
"name":"东山公交首末站",
"area":"吴中区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"金山路停保场2期",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"高新区杨巷港公交停车场",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"沪宁城际高铁新区公交首末站",
"area":"高新区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"灵岩山公交首末站（西）",
"area":"吴中区",
"startTime":"2021/09/08",
"endTime":"2021/09/08"
},
{
"name":"教育园南区公交首末站",
"area":"吴中区",
"startTime":"2019/12/11",
"endTime":"2020/02/18"
},
{
"name":"高新区东渚龙景花园公交首末站",
"area":"高新区",
"startTime":"2019/12/09",
"endTime":"2020/02/14"
}],
"numOfMapProjects":[{
"city":"南京市",
"value":"0",
"children":[
{
 "area":"六合区",
 "value":"1"
},{
 "area":"浦口区",
 "value":"0"
},{
 "area":"栖霞区",
 "value":"2"
},{
 "area":"鼓楼区",
 "value":"0"
},{
 "area":"玄武区",
 "value":"0"
},{
 "area":"建邺区",
 "value":"0"
},{
 "area":"秦淮区",
 "value":"0"
},{
 "area":"雨花台区",
 "value":"0"
},{
 "area":"江宁区",
 "value":"0"
},{
 "area":"溧水区",
 "value":"0"
},{
 "area":"高淳区",
 "value":"0"
}
]
},
{
"city":"苏州市",
"value":"0",
"children":[
{
 "area":"张家港区",
 "value":"1"
},{
 "area":"常熟区",
 "value":"0"
},{
 "area":"相城区",
 "value":"2"
},{
 "area":"太仓区",
 "value":"0"
},{
 "area":"虎丘区",
 "value":"0"
},{
 "area":"姑苏区",
 "value":"0"
},{
 "area":"工业园区",
 "value":"0"
},{
 "area":"昆山区",
 "value":"0"
},{
 "area":"吴中区",
 "value":"0"
},{
 "area":"吴江区",
 "value":"0"
}
]
},
{
"city":"无锡市",
"value":"0",
"children":[
{
 "area":"江阴市",
 "value":"1"
},{
 "area":"惠山区",
 "value":"0"
},{
 "area":"锡山区",
 "value":"2"
},{
 "area":"梁溪区",
 "value":"0"
},{
 "area":"滨湖区",
 "value":"0"
},{
 "area":"新吴区",
 "value":"0"
},{
 "area":"宜兴市",
 "value":"0"
}
]
},
{
"city":"南通市",
"value":"0",
"children":[
{
 "area":"海安市",
 "value":"1"
},{
 "area":"如皋市",
 "value":"0"
},{
 "area":"如东县",
 "value":"2"
},{
 "area":"通州区",
 "value":"0"
},{
 "area":"崇川区",
 "value":"0"
},{
 "area":"海门区",
 "value":"0"
},{
 "area":"启东市",
 "value":"0"
}
]
},
{
"city":"徐州市",
"value":"0",
"children":[
{
 "area":"丰县",
 "value":"1"
},{
 "area":"沛县",
 "value":"0"
},{
 "area":"鼓楼区",
 "value":"2"
},{
 "area":"泉山区",
 "value":"0"
},{
 "area":"云龙区",
 "value":"0"
},{
 "area":"贾汪区",
 "value":"0"
},{
 "area":"铜山区",
 "value":"0"
},{
 "area":"邳州市",
 "value":"0"
},{
 "area":"新沂市",
 "value":"0"
},{
 "area":"睢宁县",
 "value":"0"
}
]
},
{
"city":"连云港市",
"value":"0",
"children":[
{
 "area":"赣榆区",
 "value":"1"
},{
 "area":"东海县",
 "value":"0"
},{
 "area":"海州区",
 "value":"2"
},{
 "area":"连云区",
 "value":"0"
},{
 "area":"港云县",
 "value":"0"
},{
 "area":"灌南县",
 "value":"0"
}
]
},
{
"city":"淮安市",
"value":"0",
"children":[
{
 "area":"涟水区",
 "value":"1"
},{
 "area":"淮阴区",
 "value":"0"
},{
 "area":"清江浦区",
 "value":"2"
},{
 "area":"淮安区",
 "value":"0"
},{
 "area":"洪泽区",
 "value":"0"
},{
 "area":"盱眙县",
 "value":"0"
},{
 "area":"金湖县",
 "value":"0"
}
]
},
{
"city":"泰州市",
"value":"0",
"children":[
{
 "area":"兴化市",
 "value":"1"
},{
 "area":"海陵区",
 "value":"0"
},{
 "area":"姜堰区",
 "value":"2"
},{
 "area":"高港区",
 "value":"0"
},{
 "area":"泰兴市",
 "value":"0"
},{
 "area":"靖江市",
 "value":"0"
}
]
},
{
"city":"常州市",
"value":"0",
"children":[
{
 "area":"新北区",
 "value":"1"
},{
 "area":"钟楼区",
 "value":"0"
},{
 "area":"天宁区",
 "value":"2"
},{
 "area":"武进区",
 "value":"0"
},{
 "area":"金坛区",
 "value":"0"
},{
 "area":"溧阳市",
 "value":"0"
}
]
},
{
"city":"扬州市",
"value":"0",
"children":[
{
 "area":"宝应县",
 "value":"1"
},{
 "area":"高邮市",
 "value":"0"
},{
 "area":"仪征市",
 "value":"2"
},{
 "area":"邗江区",
 "value":"0"
},{
 "area":"广陵区",
 "value":"0"
},{
 "area":"江都区",
 "value":"0"
}
]
},
{
"city":"镇江市",
"value":"0",
"children":[
{
 "area":"句容市",
 "value":"1"
},{
 "area":"丹徒区",
 "value":"0"
},{
 "area":"润州区",
 "value":"2"
},{
 "area":"京口区",
 "value":"0"
},{
 "area":"扬中市",
 "value":"0"
},{
 "area":"丹阳市",
 "value":"0"
}
]
},
{
"city":"盐城市",
"value":"0",
"children":[
{
 "area":"响水县",
 "value":"1"
},{
 "area":"滨海县",
 "value":"0"
},{
 "area":"阜宁县",
 "value":"2"
},{
 "area":"射阳县",
 "value":"0"
},{
 "area":"建湖县",
 "value":"0"
},{
 "area":"亭湖区",
 "value":"0"
},{
 "area":"盐都区",
 "value":"0"
},{
 "area":"大丰区",
 "value":"0"
},{
 "area":"东台区",
 "value":"0"
}
]
},
{
"city":"宿迁市",
"value":"0",
"children":[
{
 "area":"沭阳县",
 "value":"1"
},{
 "area":"宿豫区",
 "value":"0"
},{
 "area":"宿城区",
 "value":"2"
},{
 "area":"泗阳县",
 "value":"0"
},{
 "area":"泗洪县",
 "value":"0"
}
]
}],
"totNumOfInvestProjectsIn13Cities":{
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
"numOfInvestProjectsIn13Cities":[{
"city":"南京市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"苏州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"无锡市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"南通市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"徐州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"连云港市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"淮安市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"泰州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"常州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"扬州市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"镇江市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"盐城市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
},
{
"city":"宿迁市",
"within2Million":"0",
"moreThan2Million":"0",
"provincialCoWithin2Million":"0",
"provincialCoOvr2Million":"0"
}],
"projectStsInThePast6Months":[{
"date":"10月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"09月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"08月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"07月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"06月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
},
{
"date":"05月",
"numOfNewProjects":"0",
"numOfProjectsCompleted":"0"
}],
"stationClassification":[],
"totStationClassification":"0",
"proportionOfProjectsIn13Cities":[{
"city":"南京市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"苏州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"无锡市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"南通市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"徐州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"连云港市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"淮安市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"泰州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"常州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"扬州市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"镇江市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"盐城市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
},
{
"city":"宿迁市",
"totNumOfItems":"0",
"toBeConstructed":"0",
"underConstruction":"0",
"completed":"0"
}]
};
